#! /bin/sh

### BEGIN INIT INFO
# Provides:		loom
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	Cheddar Loom HLS Repackaging Service
### END INIT INFO

set -e

# /etc/init.d/loom: start and stop the Loom HLS repackaging service

umask 022

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
	if [ "$1" = log_end_msg ]; then
	    log_end_msg 1 || true
	fi
	if ! run_by_init; then
	    log_action_msg "/dev/null is not a character device!" || true
	fi
	exit 1
    fi
}

export PATH="${PATH:+$PATH:}/usr/bin:/bin"

case "$1" in
  start)
	check_dev_null
	log_daemon_msg "Starting the Loom HLS repackaging service" "loom" || true
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/loom.pid --make-pidfile --exec /usr/bin/loom > /var/log/loom --background; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping the Loom HLS repackaging service" "loom" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/loom.pid --remove-pidfile; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting the Loom HLS repackaging service" "loom" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/loom.pid --remove-pidfile
	check_dev_null log_end_msg
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/loom.pid --make-pidfile --exec /usr/bin/loom > /var/log/loom --background; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
	status_of_proc -p /var/run/loom.pid /usr/bin/loom && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/loom {start|stop|restart|status}" || true
	exit 1
esac

exit 0
