# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3

    working_directory: /go/src/github.com/cheddartv/loom
    steps:
      - checkout
      - run: dep ensure
      - run: go test -coverprofile=c.out -v ./...
